{
    "departement": "14",
    "nom_territoire": "CC de Bidule",
    "intercommunal": "oui",
    "type_document": "PLU",
    "est_plui": "oui",
    "dans_scot": "non",
    "vaut_pdu": "oui",
    "vaut_plh": "oui",
    "dans_DTA": "DTA de truc",
    "dans_PLH": "PLH de machin",
    "dans_PPA": "PPA de Schmurz",
    "risques_technos": "oui",
    "risques_indus": "oui",
    "dans_pprt": "en cours",
    "risques_miniers": "en cours",
    "sols_pollues": "oui",
    "communes_sensibles": "oui",
    "icpe_danger": "oui",
    "itmd": "en cours",
    "risques_nat": "oui",
    "risque_inond": "oui",
    "ppri": "oui",
    "r_inond_debord": "oui",
    "r_inond_submersion": "oui",
    "r_inond_nappe": "oui",
    "r_inond_ruis": "oui",
    "papi": "oui",
    "risque_mouv_ter": "oui",
    "r_mouv_cavites": "oui",
    "r_mouv_eboul": "oui",
    "r_mouv_gliss": "oui",
    "r_mouv_argiles": "oui",
    "risque_sismique": "oui",
    "pprn": "oui",
    "risque_catnat": "oui",
    "tri": "oui",
    "slgri": "oui",
    "littoral": "oui",
    "urbain": "oui",
    "type_EE": "cpc",
    "projet_infra": ""
}
